version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo: 
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: shenoyanjana96
      MONGO_INITDB_ROOT_PASSWORD: Anjanashenoy310
      MONGO_INITDB_DATABASE: moments

      # MONGO_URI: mongodb+srv://shenoyanjana96:moments@moments.o0rfqoi.mongodb.net/moments
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local



