version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
    - frontend:/app/build

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - C:/Users/varah/Desktop/Moments/frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  mongo: 
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: shenoyanjana96
      MONGO_INITDB_ROOT_PASSWORD: Anjanashenoy310
      MONGO_INITDB_DATABASE: moments

    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
  static:
  frontend:



